### ISSUE TITLE
fail on invalid keys under the maven root

### ISSUE THREAD

**Issue by fitzoh** [fitzoh/maven-push-plugin#2]
If you accidentally use the key `repo-user` instead of `repo-username`, you will probably end up with a 401 unauthorized (likewise with `repo-url` vs `repository-url`.

`cf maven-push` should fail with a validation error if there are invalid keys under the `maven` root, but allow invalid keys elsewhere in the manifest.

this should fail validation:
```
---
applications:
- name: my-application
  maven:
    repository-url: https://repo.maven.apache.org/maven2/ #should be repo-url
    group-id: com.group.my
    artifact-id: my-artifact
    version: 1.0.0
```
this should pass validation:
```
---
applications:
- name: my-application
  invalid-key: something
  maven:
    repository-url: https://repo.maven.apache.org/maven2/
    group-id: com.group.my
    artifact-id: my-artifact
    version: 1.0.0
```
